"""schema v1

Revision ID: 7c7eb696ce86
Revises:
Create Date: 2026-08-25 07:51:21.603750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c7eb696ce86"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm backs fuzzy name lookup during deduplication; vector is created here rather
    # than in the Phase 3 migration because extension creation needs privileges the
    # migration runner has now and the application role should not keep later.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("parent_slug", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_table(
        "companies",
        sa.Column("primary_domain", sa.String(length=253), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("company_size", sa.String(length=64), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("primary_domain", name=op.f("uq_companies_primary_domain")),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "SUCCEEDED", "FAILED", "DRY_RUN", name="ingest_status"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
        sa.UniqueConstraint("run_id", name=op.f("uq_ingest_runs_run_id")),
    )
    op.create_index(
        op.f("ix_ingest_runs_source_sha256"), "ingest_runs", ["source_sha256"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("slug", sa.String(length=96), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("slug", name=op.f("uq_locations_slug")),
    )
    op.create_table(
        "category_aliases",
        sa.Column("alias_raw", sa.String(length=256), nullable=False),
        sa.Column("alias_normalized", sa.String(length=256), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_category_aliases_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category_aliases")),
        sa.UniqueConstraint("alias_normalized", name="uq_category_aliases_alias"),
    )
    op.create_index(
        op.f("ix_category_aliases_alias_normalized"),
        "category_aliases",
        ["alias_normalized"],
        unique=False,
    )
    op.create_table(
        "leads",
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("display_name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column(
            "entity_kind",
            sa.Enum("PERSON", "BUSINESS", "UNKNOWN", name="entity_kind"),
            nullable=False,
        ),
        sa.Column("is_placeholder_name", sa.Boolean(), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("location_raw", sa.String(length=128), nullable=True),
        sa.Column("location_confidence", sa.Float(), nullable=True),
        sa.Column("category_id", sa.UUID(), nullable=True),
        sa.Column("fb_category_raw", sa.String(length=256), nullable=True),
        sa.Column("niche_raw", sa.String(length=128), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_leads_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_leads_company_id_companies"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_leads_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leads")),
    )
    op.create_index("ix_leads_company_id", "leads", ["company_id"], unique=False)
    op.create_index("ix_leads_normalized_name", "leads", ["normalized_name"], unique=False)
    op.create_table(
        "location_aliases",
        sa.Column("alias_raw", sa.String(length=128), nullable=False),
        sa.Column("alias_normalized", sa.String(length=128), nullable=False),
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_location_aliases_location_id_locations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location_aliases")),
        sa.UniqueConstraint("alias_normalized", name="uq_location_aliases_alias"),
    )
    op.create_index(
        op.f("ix_location_aliases_alias_normalized"),
        "location_aliases",
        ["alias_normalized"],
        unique=False,
    )
    op.create_table(
        "data_quality_scores",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("factors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100", name=op.f("ck_data_quality_scores_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_data_quality_scores_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_scores")),
        sa.UniqueConstraint("lead_id", "rubric_version", name="uq_data_quality_lead_rubric"),
    )
    op.create_index(
        op.f("ix_data_quality_scores_lead_id"), "data_quality_scores", ["lead_id"], unique=False
    )
    op.create_table(
        "duplicate_candidates",
        sa.Column("lead_a_id", sa.UUID(), nullable=False),
        sa.Column("lead_b_id", sa.UUID(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "EXACT_EMAIL",
                "EXACT_PHONE",
                "EXACT_FACEBOOK",
                "SHARED_WEBSITE",
                "FUZZY_NAME",
                name="duplicate_method",
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED_DUPLICATE", "REJECTED_DISTINCT", name="duplicate_status"),
            nullable=False,
        ),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_duplicate_candidates_confidence_range"),
        ),
        sa.CheckConstraint(
            "lead_a_id <> lead_b_id", name=op.f("ck_duplicate_candidates_distinct_leads")
        ),
        sa.ForeignKeyConstraint(
            ["lead_a_id"],
            ["leads.id"],
            name=op.f("fk_duplicate_candidates_lead_a_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_b_id"],
            ["leads.id"],
            name=op.f("fk_duplicate_candidates_lead_b_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_duplicate_candidates")),
        sa.UniqueConstraint("lead_a_id", "lead_b_id", "method", name="uq_duplicate_candidate_pair"),
    )
    op.create_index(
        "ix_duplicate_candidates_status", "duplicate_candidates", ["status"], unique=False
    )
    op.create_table(
        "eval_labels",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("dimension", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column(
            "label_source",
            sa.Enum("WEAK_RELEVANCE", "HUMAN_GOLD", name="label_source"),
            nullable=False,
        ),
        sa.Column("labeller", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"], ["leads.id"], name=op.f("fk_eval_labels_lead_id_leads"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_labels")),
        sa.UniqueConstraint("lead_id", "dimension", "label_source", name="uq_eval_label"),
    )
    op.create_index(op.f("ix_eval_labels_lead_id"), "eval_labels", ["lead_id"], unique=False)
    op.create_table(
        "lead_identifiers",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "EMAIL",
                "PHONE",
                "WHATSAPP",
                "WEBSITE",
                "FACEBOOK",
                "INSTAGRAM",
                "YOUTUBE",
                "LINKEDIN",
                name="identifier_kind",
            ),
            nullable=False,
        ),
        sa.Column("value_raw", sa.Text(), nullable=False),
        sa.Column("value_normalized", sa.Text(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_valid", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_lead_identifiers_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_lead_identifiers_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_identifiers")),
        sa.UniqueConstraint("lead_id", "kind", "value_normalized", name="uq_lead_identifier"),
    )
    op.create_index(
        "ix_lead_identifiers_kind_value",
        "lead_identifiers",
        ["kind", "value_normalized"],
        unique=False,
    )
    op.create_table(
        "lead_source_queries",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("query", sa.String(length=256), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_is_inferred", sa.Boolean(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_lead_source_queries_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_source_queries")),
        sa.UniqueConstraint("lead_id", "query", "source", name="uq_lead_source_query"),
    )
    op.create_table(
        "lead_source_records",
        sa.Column("ingest_run_id", sa.UUID(), nullable=False),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("source_file", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_sheet", sa.String(length=64), nullable=False),
        sa.Column("source_row_no", sa.Integer(), nullable=False),
        sa.Column("source_serial", sa.String(length=32), nullable=True),
        sa.Column("row_sha256", sa.String(length=64), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ingest_run_id"],
            ["ingest_runs.id"],
            name=op.f("fk_lead_source_records_ingest_run_id_ingest_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_lead_source_records_lead_id_leads"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lead_source_records")),
        sa.UniqueConstraint(
            "source_sha256", "source_sheet", "source_row_no", name="uq_lead_source_record_cell"
        ),
    )
    op.create_index(
        op.f("ix_lead_source_records_lead_id"), "lead_source_records", ["lead_id"], unique=False
    )
    op.create_index(
        "ix_lead_source_records_row_sha", "lead_source_records", ["row_sha256"], unique=False
    )
    op.create_table(
        "metric_observations",
        sa.Column("lead_id", sa.UUID(), nullable=False),
        sa.Column("metric", sa.Enum("FOLLOWERS", name="metric_kind"), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("value_raw", sa.String(length=32), nullable=False),
        sa.Column("batch", sa.String(length=64), nullable=False),
        sa.Column("batch_sequence", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_metric_observations_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_metric_observations")),
        sa.UniqueConstraint("lead_id", "metric", "batch", name="uq_metric_observation"),
    )
    op.create_index(
        "ix_metric_observations_lead_metric",
        "metric_observations",
        ["lead_id", "metric"],
        unique=False,
    )
    op.create_table(
        "validation_issues",
        sa.Column("source_record_id", sa.UUID(), nullable=True),
        sa.Column("lead_id", sa.UUID(), nullable=True),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("INFO", "WARNING", "ERROR", name="validation_severity"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("value_raw", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["lead_id"],
            ["leads.id"],
            name=op.f("fk_validation_issues_lead_id_leads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["lead_source_records.id"],
            name=op.f("fk_validation_issues_source_record_id_lead_source_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_issues")),
    )
    op.create_index("ix_validation_issues_code", "validation_issues", ["code"], unique=False)
    op.create_index("ix_validation_issues_lead_id", "validation_issues", ["lead_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_validation_issues_lead_id", table_name="validation_issues")
    op.drop_index("ix_validation_issues_code", table_name="validation_issues")
    op.drop_table("validation_issues")
    op.drop_index("ix_metric_observations_lead_metric", table_name="metric_observations")
    op.drop_table("metric_observations")
    op.drop_index("ix_lead_source_records_row_sha", table_name="lead_source_records")
    op.drop_index(op.f("ix_lead_source_records_lead_id"), table_name="lead_source_records")
    op.drop_table("lead_source_records")
    op.drop_table("lead_source_queries")
    op.drop_index("ix_lead_identifiers_kind_value", table_name="lead_identifiers")
    op.drop_table("lead_identifiers")
    op.drop_index(op.f("ix_eval_labels_lead_id"), table_name="eval_labels")
    op.drop_table("eval_labels")
    op.drop_index("ix_duplicate_candidates_status", table_name="duplicate_candidates")
    op.drop_table("duplicate_candidates")
    op.drop_index(op.f("ix_data_quality_scores_lead_id"), table_name="data_quality_scores")
    op.drop_table("data_quality_scores")
    op.drop_index(op.f("ix_location_aliases_alias_normalized"), table_name="location_aliases")
    op.drop_table("location_aliases")
    op.drop_index("ix_leads_normalized_name", table_name="leads")
    op.drop_index("ix_leads_company_id", table_name="leads")
    op.drop_table("leads")
    op.drop_index(op.f("ix_category_aliases_alias_normalized"), table_name="category_aliases")
    op.drop_table("category_aliases")
    op.drop_table("locations")
    op.drop_index(op.f("ix_ingest_runs_source_sha256"), table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("companies")
    op.drop_table("categories")
    # ### end Alembic commands ###
    # Autogenerate does not drop native enum types; without this a downgrade followed by an
    # upgrade fails with "type already exists".
    for enum_name in (
        "entity_kind",
        "identifier_kind",
        "metric_kind",
        "validation_severity",
        "duplicate_method",
        "duplicate_status",
        "label_source",
        "ingest_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
