"""schema v2 verification caches

Revision ID: 34b5acd820d9
Revises: 7c7eb696ce86
Create Date: 2026-08-25 08:40:50.672915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "34b5acd820d9"
down_revision: Union[str, Sequence[str], None] = "7c7eb696ce86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_verifications",
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column(
            "status",
            sa.Enum("VERIFIED", "UNREACHABLE", "UNKNOWN", "SKIPPED", name="verification_status"),
            nullable=False,
        ),
        sa.Column("has_mx", sa.Boolean(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "GOOGLE",
                "MICROSOFT",
                "ZOHO",
                "YANDEX",
                "PROOFPOINT",
                "MIMECAST",
                "GODADDY",
                "HOSTINGER",
                "REDIFF",
                "SELF_HOSTED",
                "OTHER",
                "NONE",
                name="mail_provider",
            ),
            nullable=False,
        ),
        sa.Column("is_freemail", sa.Boolean(), nullable=False),
        sa.Column("is_disposable", sa.Boolean(), nullable=False),
        sa.Column("address_count", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latency_ms >= 0", name=op.f("ck_domain_verifications_latency_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_domain_verifications")),
        sa.UniqueConstraint("domain", name=op.f("uq_domain_verifications_domain")),
    )
    op.create_index(
        "ix_domain_verifications_expires_at", "domain_verifications", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_domain_verifications_status", "domain_verifications", ["status"], unique=False
    )
    op.create_table(
        "url_verifications",
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column(
            "status",
            sa.Enum("VERIFIED", "UNREACHABLE", "UNKNOWN", "SKIPPED", name="verification_status"),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("is_live", sa.Boolean(), nullable=False),
        sa.Column("is_parked", sa.Boolean(), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("redirect_count", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_url_verifications")),
        sa.UniqueConstraint("url", name=op.f("uq_url_verifications_url")),
    )
    op.create_index(
        "ix_url_verifications_expires_at", "url_verifications", ["expires_at"], unique=False
    )
    op.create_index("ix_url_verifications_host", "url_verifications", ["host"], unique=False)
    op.create_index("ix_url_verifications_status", "url_verifications", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_url_verifications_status", table_name="url_verifications")
    op.drop_index("ix_url_verifications_host", table_name="url_verifications")
    op.drop_index("ix_url_verifications_expires_at", table_name="url_verifications")
    op.drop_table("url_verifications")
    op.drop_index("ix_domain_verifications_status", table_name="domain_verifications")
    op.drop_index("ix_domain_verifications_expires_at", table_name="domain_verifications")
    op.drop_table("domain_verifications")
    # ### end Alembic commands ###
    for enum_name in ("verification_status", "mail_provider"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
